---
title: "Data 2019"
author: "David Adeyemo"
date: "2/28/2022"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(here)
library(stringr)
library(urbnmapr)
library(lubridate)
```
# 2019 data

```{r}
read.csv(
  here("Data", "FARS2019/ACCIDENT.CSV"), sep = ",",
  header = TRUE
  ) %>%
  clean_names() -> accident_2019

read.csv(
  here("Data", "FARS2019/VEHICLE.CSV"), sep = ",",
  header = TRUE
  ) %>%
  clean_names() -> vehicle_2019

read.csv(
  here("Data", "FARS2019/PERSON.CSV"), sep = ",",
  header = TRUE
  ) %>%
  clean_names() -> person_2019
```

```{r}
accident_2019 %>%
  select(1, 3, 5, 11, 13, 15, 17, 19, 20, 22, 24, 28, 30, 40, 42,
         46, 48, 50, 52, 54, 56, 58, 60, 66, 68, 72, 74, 76, 78,
         80, 82, 84, 86, 88, 90, 91) -> accident_2019
```
```{r}
person_2019 %>% 
  select(
    1:3, 5, 6, 9, 10, 15, 16, 24, 37:39, 41:44, 46:50, 52, 53
    ) -> person_2019
```

```{r}
vehicle_2019 %>% 
  select(
  1, 3:6, 8, 10, 12, 14, 16, 18, 28, 31, 33, 35, 51, 79, 81,
  87, 91, 103, 22, 20, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77,
  83, 85, 89, 93, 95, 97, 99, 101, 165,167, 169, 171, 173, 175, 177,
  179, 181, 183, 185, 187, 189, 190
  ) -> vehicle_2019
```
```{r}
intersect(
  colnames(accident_2019),
  colnames(person_2019)
)

accident_2019 %>% 
  left_join(
    person_2019, by = c("state", "st_case", "day", "minute")
  ) -> accident_person_2019
```
```{r}
intersect(
  colnames(accident_person_2019),
  colnames(vehicle_2019)
)

accident_person_2019 %>% 
  left_join(
    vehicle_2019, by = c(
      "state", "st_case", "ve_forms", "day", "month",
      "hour", "minute", "harm_ev", "man_coll", "veh_no",
      "emer_use", "impact1", "fire_exp"
    )
  ) -> accident_person_vehicle_2019
```
```{r}
accident_person_vehicle_2019 -> apv_2019
```

```{r}
save(apv_2019, file = "Data/FARS2019/apv_2019.RData")
```
```{r}
data(states)
colnames(states)

states %>%
  distinct(
    state_fips, state_abbv, state_name
    ) -> stdf

apv_2019 %>%
  mutate(
    state_fips = stringr::str_pad(
      state, width = 2, side = "left", pad = "0")
    ) -> apv_2019_01

apv_2019_01 %>% relocate(
  state, state_fips, statename
) -> apv_2019_01

apv_2019_01 %>% select(-state) -> apv_2019_01

apv_2019_01 %>% 
  left_join(
    stdf, by = "state_fips"
  ) -> apv_2019_01

apv_2019_01 %>% 
  relocate(
    state_abbv, state_name, .after = state_fips
    ) %>% select(
      -statename
    ) -> apv_2019_02
```
```{r}
apv_2019_02 %>% 
  mutate(
    date = paste(year, month, day, sep = "-"),
    time = paste(hour, minute, 0, sep = "-")
  ) %>% relocate(
    date, time, year, month, day, hour, minute
  ) -> apv_2019_03

```
```{r}
apv_2019_03 %>% 
  mutate(
    date_time = paste(date, time, sep = ":"),
    date_time = lubridate::ymd_hms(date_time)
  ) %>% relocate(
    date_time
  ) -> apv_2019_04
```
```{r}
apv_2019_04 %>% 
  select(
    -c(year, month, day, date, hour, minute, time)
  ) -> apv_2019_05
```
```{r}
apv_2019_05 %>% 
  mutate(day_of_week = lubridate::wday(
    date_time,
    label = TRUE,
    abbr = FALSE
  ) 
  )%>% relocate(
    date_time, day_of_week
  ) %>% select(
    -c(day_week)
  ) -> apv_2019_06
```
```{r}
apv_2019_06 %>%
  mutate(
    route = case_when(
      route == 1 ~ "Interstate",
      route == 2 ~ "U.S. Highway",
      route == 3 ~ "State Highway",
      route == 4 ~ "County Highway",
      route == 5 ~ "Local Street - Township",
      route == 6 ~ "Local Street - Municipality",
      route == 7 ~ "Local Street - Frontage",
      route == 8 ~ "Other",
      route == 9 ~ "Unknown"
      ),
    sch_bus = case_when(
      sch_bus == 0 ~ "School Bus Not Involved",
      sch_bus == 1 ~ "School Bus Involved"
      )
    ) -> apv_2019_07 

```
```{r}
library(urbnmapr)
data("counties")

counties %>% distinct(
  state_fips, state_name, county_name
) -> county.df
```









